### ISSUE TITLE
{Batch Note Editing] Unable to attach images from clipboard in Anki 2.1

### ISSUE THREAD

**Issue by donfed** [glutanimate/batch-editing#5]
## Which add-on is affected?

[ Please mention the add-on in the issue title as follows: "[Add-on name] My issue" ]

## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [x ] In case of a bug: Have you tried restarting Anki?
- [ x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x ] Did you check the add-on description on AnkiWeb for known issues?
- [x ] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

In batch note edit on anki 2.1.4 (stable release), unable to insert image from clipboard as addition to multiple cards (previously working on anki 2.0). Debug info/error message:

Debug info:
Anki 2.1.4 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "C:\Users\setup\AppData\Roaming\Anki2\addons21\291119185\browser_batch_edit.py", line 101, in _insertMedia
    media_file = self._getClip()
  File "C:\Users\setup\AppData\Roaming\Anki2\addons21\291119185\browser_batch_edit.py", line 135, in _getClip
    return unicode(image_path)
<class 'NameError'>: name 'unicode' is not defined

## How can we reproduce the problem?

Image capture to clipboard using either snipping tool or onenote screen clipping or copy image directly from other source and then click attach button on batch edit interface.

**Expected behavior:** Insert clipboard image to batch edit "content to add or replace with"

**Actual behavior:** Error message above.

**Reproducible?:** Yes, restarts of anki and pc, enable/disable/reinstall addon, multiple clipboard attempts

## Version information
Version 2.1.4
Qt 5.9.2 PyQt 5.9
Windows 10- 64bit

**Comment by glutanimate** [comment]
Thanks again for the reports guys, and sorry that it took me a bit longer to respond. These issues should now be fixed in the latest add-on release (both available via GitHub and AnkiWeb).

P.S.: You can now follow [@AnkiUpdates](https://twitter.com/AnkiUpdates) on Twitter to stay up-to-date with my add-on releases.

**Comment by ExtremeCoolDude** [comment]
Sorry for necrodumping on an old post. Came to here via google. 

I'm unable to copy paste an image from clipboard in the latest version of anki with latest version from ankiweb.  Using Anki on Linux.

The paste option is grayed out and nothing happens when I paste Ctrl + V.

**Comment by berserkerezio** [comment]
i am having a similar trouble again. Can't add image from clipboard(using snip tool or copying an image from within another anki note). Instead of adding an image on pressing ctrl+v(for images copied from another anki card),only blank lines are added(i.e. it acts as if i am pressing enter and creating new lines) or no action occurs. Using the top right pin button(for images copied from anywhere, snip tool or anki note or hard drive) simply opens file selector.
The issue is not related to any other add-on as far as I have tried disabling them all, still the problem persists.
I can't try it on another device, don't have another one.
i have already tried installing manually from github, still the same problem.

OS-windows 10
Anki 2.1.35
